workflows:
  build-ios:
    name: Build iOS
    environment:
      flutter: stable
      xcode: latest
      groups:
        - secrets
    scripts:
      - name: Generate secrets.dart
        script: |
          echo "const clientSecret = '${ANILIST_CLIENT_SECRET}';" > lib/secrets.dart
      - name: 'Flutter pub get'
        script: flutter pub get
      - name: 'Build iOS'
        script: flutter build ios --no-codesign
      - name: Create IPA
        script: |
          VERSION=$(grep '^version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          cd Payload
          zip -r ../AnimeShin-v${VERSION}.ipa .
          cd ..
    artifacts:
      - AnimeShin-v*.ipa
